table benefits
	lineageTag: 02dfed16-22e4-4724-b2a1-786394ad8673

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: bf3aad52-8bd4-47d0-a572-8efd37a827e6
		summarizeBy: none
		sourceColumn: job_id

		annotation SummarizationSetBy = Automatic

	column inferred
		dataType: int64
		formatString: 0
		lineageTag: 1fef85f0-e063-4229-833a-c1e0a88b2330
		summarizeBy: sum
		sourceColumn: inferred

		annotation SummarizationSetBy = Automatic

	column type
		dataType: string
		lineageTag: 3ff5560e-7af0-4e6b-a5a7-bf30f90592df
		summarizeBy: none
		sourceColumn: type

		annotation SummarizationSetBy = Automatic

	partition benefits = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ilias\OneDrive\Desktop\ilia\power bi\linkedin job postings\static datasets\benefits.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_id", Int64.Type}, {"inferred", Int64.Type}, {"type", type text}}),
				    #"Removed Duplicates" = Table.Distinct(#"Changed Type", {"job_id", "type"})
				in
				    #"Removed Duplicates"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

