table job_skills
	lineageTag: ea0addb2-cbaa-4ed5-8430-31c49d16a7c8

	column job_id
		dataType: int64
		formatString: 0
		lineageTag: 4ca50e67-db2c-4988-8202-2742e6ca0294
		summarizeBy: none
		sourceColumn: job_id

		annotation SummarizationSetBy = Automatic

	column skill_abr
		dataType: string
		lineageTag: 31c5cf68-de4a-483e-b1aa-b8e7611f2b88
		summarizeBy: none
		sourceColumn: skill_abr

		annotation SummarizationSetBy = Automatic

	partition job_skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ilias\OneDrive\Desktop\ilia\power bi\linkedin job postings\static datasets\job_skills.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"job_id", Int64.Type}, {"skill_abr", type text}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

