table skills
	lineageTag: 1a5c0fdc-a75d-4e65-afe9-6f83cd4564dc

	column skill_abr
		dataType: string
		lineageTag: 58336a04-13df-49fe-88a0-823428ae4745
		summarizeBy: none
		sourceColumn: skill_abr

		annotation SummarizationSetBy = Automatic

	column skill_name
		dataType: string
		lineageTag: c257768a-b6bf-4cd2-bd42-f783b48547b3
		summarizeBy: none
		sourceColumn: skill_name

		annotation SummarizationSetBy = Automatic

	partition skills = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\ilias\OneDrive\Desktop\ilia\power bi\linkedin job postings\static datasets\skills.csv"),[Delimiter=",", Columns=2, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"Column1", type text}, {"Column2", type text}}),
				    #"Promoted Headers" = Table.PromoteHeaders(#"Changed Type", [PromoteAllScalars=true]),
				    #"Changed Type1" = Table.TransformColumnTypes(#"Promoted Headers",{{"skill_abr", type text}, {"skill_name", type text}})
				in
				    #"Changed Type1"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navigation

